import { useState } from 'react';
import { KeyRound, Plus, UserCog } from 'lucide-react';
import { post, put } from '../../../services/api.js';
import { Button, DataTable, ErrorState, Field, inputClass, Modal, PageHeader, StatusBadge, useNotice } from '../../../components/ui/index.jsx';
import { useApiData } from '../../../hooks/useApiData.js';

const userBlank = { username: "", fullName: "", email: "", role: "INITIATOR", password: "", enabled: true, memberId: "" };
export default function UsersPage() {
  const users=useApiData('/admin/users');
  const members=useApiData('/members');
  const notify=useNotice();
  const [userModal, setUserModal] = useState(null);
  const [userForm, setUserForm] = useState(userBlank);
  const [passwordUser, setPasswordUser] = useState(null);
  const [newPassword, setNewPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error,setError]=useState('');
  const openUser = (user = null) => { setError(''); setUserModal(user || "new"); setUserForm(user ? { ...user, password: "", memberId: user.memberId || "" } : userBlank); };
  const saveUser = async (event) => { event.preventDefault(); setBusy(true); try { const payload = { ...userForm, memberId: userForm.memberId ? Number(userForm.memberId) : null, password: userForm.password || null }; if (userModal === "new") await post("/admin/users", payload); else await put(`/admin/users/${userModal.id}`, payload); notify(userModal === "new" ? "User created" : "User updated"); setUserModal(null); users.reload(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const savePassword = async (event) => { event.preventDefault(); setBusy(true); try { await post(`/admin/users/${passwordUser.id}/password`, { password: newPassword }); notify("Password updated; previous sessions were closed"); setPasswordUser(null); setNewPassword(""); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const toggle=async row=>{setBusy(true);setError('');try{await put(`/admin/users/${row.id}`,{...row,password:null,enabled:!row.enabled});users.reload();notify('Account status updated');}catch(e){setError(e.message);}finally{setBusy(false);}};
  if(users.error||members.error)return <ErrorState message={users.error||members.error} onRetry={()=>{users.reload();members.reload();}}/>;
  return <><PageHeader title="Users" description="System Settings · Manage staff accounts, roles and access." actions={<Button disabled={busy||users.loading||members.loading} onClick={()=>openUser()}><Plus size={16}/>Add user</Button>}/>
  {error&&!userModal&&!passwordUser&&<ErrorState message={error}/>}
<DataTable label="Users" loading={users.loading||members.loading} rows={users.data} columns={[{ key: "username", label: "Username", className: "font-semibold text-teal-800" }, { key: "fullName", label: "Full name" }, { key: "email", label: "Email" }, { key: "role", label: "Role", render: (row) => <StatusBadge value={row.role} /> }, { key: "enabled", label: "Account", render: (row) => <StatusBadge value={row.enabled ? "ACTIVE" : "DISABLED"} /> }, { key: "actions", label: "Actions", render: (row) => <div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => openUser(row)}><UserCog size={15} />Edit</Button><Button size="sm" variant="ghost" onClick={() => {setError('');setNewPassword('');setPasswordUser(row);}}><KeyRound size={15} />Password</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>toggle(row)}>{row.enabled?'Deactivate':'Activate'}</Button></div> }]} />
      <Modal open={Boolean(userModal)} onClose={() => !busy && setUserModal(null)} title={userModal === "new" ? "Create user" : "Update user"} size="lg"><form onSubmit={saveUser} className="grid gap-4 sm:grid-cols-2">{error&&<div className="sm:col-span-2"><ErrorState message={error}/></div>}<Field label="Username" required><input className={inputClass} value={userForm.username} onChange={(e) => setUserForm({ ...userForm, username: e.target.value })} required /></Field><Field label="Full name" required><input className={inputClass} value={userForm.fullName} onChange={(e) => setUserForm({ ...userForm, fullName: e.target.value })} required /></Field><Field label="Email" required><input type="email" className={inputClass} value={userForm.email} onChange={(e) => setUserForm({ ...userForm, email: e.target.value })} required /></Field><Field label="Role" required><select className={inputClass} value={userForm.role} onChange={(e) => setUserForm({ ...userForm, role: e.target.value })}><option>MEMBER</option><option>INITIATOR</option><option>APPROVER</option><option>ADMIN</option></select></Field>{userForm.role === "MEMBER" && <Field label="Linked member" required className="sm:col-span-2"><select className={inputClass} value={userForm.memberId} onChange={(e) => setUserForm({ ...userForm, memberId: e.target.value })} required><option value="">Select member</option>{(members.data||[]).map((member) => <option key={member.id} value={member.id}>{member.memberCode} — {member.fullName}</option>)}</select></Field>}<Field label={userModal === "new" ? "Temporary password" : "New password (optional)"} required={userModal === "new"}><input type="password" minLength="8" className={inputClass} value={userForm.password} onChange={(e) => setUserForm({ ...userForm, password: e.target.value })} required={userModal === "new"} /></Field><label className="mt-6 flex items-center gap-2 text-sm font-medium text-slate-600"><input type="checkbox" className="size-4 accent-teal-700" checked={userForm.enabled} onChange={(e) => setUserForm({ ...userForm, enabled: e.target.checked })} />Account is active</label><div className="flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-4 sm:col-span-2"><Button type="button" variant="secondary" onClick={() => setUserModal(null)}>Cancel</Button><Button type="submit" loading={busy}>Save user</Button></div></form></Modal>

      <Modal open={Boolean(passwordUser)} onClose={() => !busy && setPasswordUser(null)} title="Reset password" description={passwordUser?.fullName} size="sm"><form onSubmit={savePassword} className="space-y-4">{error&&<ErrorState message={error}/>}<Field label="New password" required hint="Minimum 8 characters"><input type="password" minLength="8" className={inputClass} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} required /></Field><p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-700">All active sessions for this user will be closed.</p><div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setPasswordUser(null)}>Cancel</Button><Button type="submit" loading={busy}>Update password</Button></div></form></Modal>


</>;
}
