import { useEffect, useState } from 'react';
import { post } from '../../../services/api.js';
import { useApiData } from '../../../hooks/useApiData.js';
import { Button, Card, DataTable, ErrorState, Field, inputClass, Loading, MoneyCell, StatusBadge, textareaClass } from '../../../components/ui/index.jsx';
import { thisMonth, money } from '../../../utils/index.js';
import ApprovalActions from '../../approvals/components/ApprovalActions.jsx';
export default function MonthlyRepayments({ canPrepare,onDone }) {
  const [period,setPeriod]=useState(thisMonth()),[remarks,setRemarks]=useState(''),[selected,setSelected]=useState({}),[amounts,setAmounts]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const due=useApiData(`/loans/due-installments?period=${period}`),batches=useApiData('/loans/repayment-batches');
  useEffect(()=>{setSelected(Object.fromEntries((due.data||[]).map(r=>[r.scheduleId,true])));setAmounts(Object.fromEntries((due.data||[]).map(r=>[r.scheduleId,r.amount])));},[due.data]);
  const done=()=>{due.reload();batches.reload();onDone();};
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const items=due.data.filter(r=>selected[r.scheduleId]).map(r=>({loanId:r.loanId,scheduleId:r.scheduleId,amount:Number(amounts[r.scheduleId])}));if(!items.length)throw new Error('Select at least one due installment');const batch=await post('/loans/repayment-batches',{period,remarks,items});await post(`/loans/repayment-batches/${batch.id}/submit`);setRemarks('');done();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const submitDraft=async id=>{setBusy(true);setError('');try{await post(`/loans/repayment-batches/${id}/submit`);done();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="space-y-5">{error&&<ErrorState message={error}/>}{canPrepare&&<Card><h2 className="mb-3 font-bold">Prepare monthly repayment batch</h2><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Field label="Repayment month" required><select className={inputClass} value={period.slice(5)} onChange={e=>setPeriod(`${period.slice(0,4)}-${e.target.value}`)}>{Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0')).map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Repayment year" required><select className={inputClass} value={period.slice(0,4)} onChange={e=>setPeriod(`${e.target.value}-${period.slice(5)}`)}>{Array.from({length:21},(_,i)=>new Date().getFullYear()-10+i).map(y=><option key={y}>{y}</option>)}</select></Field><Field label="Description / remarks" required><textarea className={textareaClass} required maxLength={500} value={remarks} onChange={e=>setRemarks(e.target.value)}/></Field></div>
    {due.loading?<Loading/>:due.error?<ErrorState message={due.error} onRetry={due.reload}/>:<DataTable rows={due.data} keyField="scheduleId" pageSize={10} columns={[
      {key:'include',label:'Include',render:r=><input aria-label={`Include ${r.memberName}`} type="checkbox" checked={Boolean(selected[r.scheduleId])} onChange={e=>setSelected({...selected,[r.scheduleId]:e.target.checked})}/>},
      {key:'memberCode',label:'Staff ID'},{key:'memberName',label:'Staff name'},{key:'loanNumber',label:'Loan'},{key:'installmentNumber',label:'Installment'},
      ...[['principal','Principal due'],['interest','Interest due'],['amount','Installment due'],['outstandingBalance','Outstanding']].map(([key,label])=>({key,label,render:r=><MoneyCell value={r[key]}/>})),
      {key:'payment',label:'Amount paid',render:r=><input aria-label={`Amount for ${r.memberName}`} className={`${inputClass} w-36`} type="number" min="0.01" max={r.amount} step="0.01" required disabled={!selected[r.scheduleId]} value={amounts[r.scheduleId]??''} onChange={e=>setAmounts({...amounts,[r.scheduleId]:e.target.value})}/>}
    ]}/>}
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between rounded-xl bg-teal-50 p-4"><div><p className="text-xs text-teal-700">Selected staff: {(due.data||[]).filter(r=>selected[r.scheduleId]).length}</p><p className="font-bold">{money((due.data||[]).filter(r=>selected[r.scheduleId]).reduce((sum,r)=>sum+Number(amounts[r.scheduleId]||0),0))}</p></div><Button type="submit" loading={busy} disabled={due.loading||Boolean(due.error)}>Submit batch for approval</Button></div>
  </form></Card>}
  <h2 className="font-bold">Repayment batches</h2>{batches.loading?<Loading/>:batches.error?<ErrorState message={batches.error} onRetry={batches.reload}/>:<DataTable rows={batches.data} columns={[{key:'period',label:'Period'},{key:'remarks',label:'Description'},{key:'createdBy',label:'Initiated by'},{key:'totalAmount',label:'Total',render:r=><MoneyCell value={r.totalAmount}/>},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>},{key:'actions',label:'Actions',render:r=><div className="flex gap-2"><ApprovalActions type="REPAYMENT_BATCH" record={r} batchItemsPath={`/loans/repayment-batches/${r.id}/items`} onDone={done}/>{canPrepare&&['DRAFT','REJECTED'].includes(r.status)&&<Button size="sm" disabled={busy} onClick={()=>submitDraft(r.id)}>Submit</Button>}</div>} ]}/>}
  </div>;
}
